import type { IArchitecture, ICycle, ISubsystem } from "./architecture.types";
import { safeNodeId } from "./mermaid";

/**
 * Subsystems drawn in the overview diagram.
 *
 * Curated because the full graph is 27 nodes and 134 edges — rendered whole it is a
 * hairball nobody reads. These are the ones a request actually travels through.
 * `lib` is left out on purpose: 24 subsystems import it, so drawing it turns every
 * layout into a star and hides the flow. The table below the diagram is the complete
 * record; this is the shape.
 */
const SPINE = [
  "(root)",
  "cli",
  "loop",
  "agent",
  "inference",
  "gate",
  "validate",
  "rule-packs",
  "stack-detection",
] as const;

const BANNER =
  "<!-- Generated by `bun run arch:build` from packages/core/src. Do not edit by hand. -->";

/**
 * Mermaid node ids must be identifier-safe — subsystem ids contain `-` and `()` — and
 * must not collide with the flowchart grammar. `safeNodeId` prefixes every id so a
 * subsystem named `class` or `end` cannot silently break the diagram at render time,
 * where neither `astro build` nor CI would notice.
 */
function nodeId(id: string): string {
  return safeNodeId(id);
}

function overviewDiagram(arch: IArchitecture): string {
  const inSpine = new Set<string>(SPINE);
  const edges = arch.edges
    .filter((e) => inSpine.has(e.from) && inSpine.has(e.to))
    .map((e) => `  ${nodeId(e.from)} --> ${nodeId(e.to)}`);

  const nodes = SPINE.map((id) => `  ${nodeId(id)}["${id}"]`);

  return [
    "```mermaid",
    "flowchart LR",
    ...nodes,
    ...[...new Set(edges)].sort(),
    "```",
  ].join("\n");
}

function subsystemTable(subsystems: readonly ISubsystem[]): string {
  const rows = subsystems.map((s) => {
    const orphan = s.fanIn === 0 && s.fanOut === 0 ? " ⚠️" : "";

    return `| \`${s.id}\`${orphan} | ${s.purpose} | ${s.tier} | ${s.files} | ${s.lines} | ${s.fanIn} | ${s.fanOut} |`;
  });

  return [
    "| Subsystem | Purpose | Tier | Files | Lines | Fan-in | Fan-out |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

function cycleTable(cycles: readonly ICycle[]): string {
  const rows = cycles.map(
    (c) =>
      `| \`${c.a}\` ↔ \`${c.b}\` | \`${c.aToB.witness}\` → \`${c.aToB.specifier}\` | ` +
      `\`${c.bToA.witness}\` → \`${c.bToA.specifier}\` |`
  );

  return [
    "| Pair | One way | The other |",
    "| --- | --- | --- |",
    ...rows,
  ].join("\n");
}

/** Render the whole map as the Markdown written to `packages/core/ARCHITECTURE.md`. */
export function renderArchitectureMd(arch: IArchitecture): string {
  const orphans = arch.subsystems.filter(
    (s) => s.fanIn === 0 && s.fanOut === 0
  );

  const out: string[] = [
    "# Architecture map",
    "",
    BANNER,
    "",
    `Derived from \`packages/core/src\`: **${arch.subsystems.length} subsystems**, ` +
      `**${arch.totalFiles} files**, **${arch.totalLines} lines**, ` +
      `**${arch.edges.length} cross-subsystem edges**.`,
    "",
    "## How a request moves",
    "",
    "The spine only — the subsystems a task actually travels through. `lib` is omitted",
    "because 24 subsystems import it and drawing it hides every other relationship.",
    "The table below is the complete record.",
    "",
    overviewDiagram(arch),
    "",
    "## Subsystems",
    "",
    subsystemTable(arch.subsystems),
    "",
  ];

  if (orphans.length > 0) {
    out.push(
      "⚠️ marks a subsystem with no imports in either direction inside `src/`. That does",
      "not make it dead — it may be reached only from `tests/` or `scripts/` — but it does",
      "mean the running harness never pulls it in.",
      ""
    );
  }

  out.push(
    "## Mutual dependencies",
    "",
    "Pairs that import each other, with the line proving each direction. Only mutual",
    "pairs are listed: longer cycles exist in a graph this dense, and enumerating them",
    "buries the ones someone can actually go and break.",
    "",
    cycleTable(arch.cycles),
    "",
    "## Adapter seams",
    "",
    "The interfaces an adapter fills in. The core loop may not import an adapter —",
    "`@typescript-eslint/no-restricted-imports` in `eslint.config.js` enforces it — so",
    "everything stack-specific arrives through one of these.",
    "",
    "| Seam | Declared | Files referencing it |",
    "| --- | --- | --- |",
    ...arch.seams.map(
      (s) =>
        `| \`${s.name}\` | \`${s.declaredAt}\` | ${s.implementors.length} |`
    ),
    "",
    "## Entry points",
    "",
    "Async functions returning an exit code, declared under the CLI — the commands.",
    "",
    "| Function | Declared |",
    "| --- | --- |",
    ...arch.entryPoints.map((e) => `| \`${e.fn}\` | \`${e.at}\` |`),
    ""
  );

  if (arch.externals.length > 0) {
    out.push(
      "## Imports that leave `src/`",
      "",
      "`src/` reaching into `scripts/` inverts the house rule that scripts orchestrate",
      "and `src/` decides — logic imported this way sits where tests are not looking.",
      "",
      "| From | Import | Target |",
      "| --- | --- | --- |",
      ...arch.externals.map(
        (e) => `| \`${e.from}\` | \`${e.witness}\` | \`${e.target}\` |`
      ),
      ""
    );
  }

  out.push(
    "## What this map does not cover",
    "",
    "Stated so a gap is not mistaken for a clean result:",
    "",
    "- Dynamic `import()` and `createRequire` are not followed — only static imports.",
    "- `tests/` and `scripts/` are not scanned; only imports *into* them are noted above.",
    "- Coupling through shared global state or the filesystem is invisible here.",
    "- Only mutual dependency pairs are reported, not longer cycles.",
    ""
  );

  return out.join("\n");
}
