import type { IArchitecture, ICycle, ISubsystem } from "./architecture.types";

const BANNER =
  "<!-- Generated by `bun run arch:build` from packages/core/src. Do not edit by hand. -->";

/**
 * This file deliberately draws NO overview diagram.
 *
 * An earlier version rendered a filtered import graph: 9 subsystems, 27 edges, laid out
 * as a bowl of spaghetti that told a reader nothing. The problem was not the layout. An
 * import graph is the wrong picture — import direction is not conceptual flow, and in a
 * codebase this size nearly everything imports nearly everything, so any honest rendering
 * of it approaches a complete graph.
 *
 * A useful system diagram is a MODEL of the system, which means someone has to decide
 * what matters and what to leave out. That is authorship, not derivation, so it lives in
 * `apps/docs/src/content/docs/internals/index.mdx` where a human maintains it.
 *
 * What a generator is good at is exactly what stays here: exhaustive tables, exact
 * counts, and a `file:line` witness for every claim. Do not reintroduce an auto-drawn
 * graph; it will be a hairball again.
 */

/**
 * Line counts to the nearest thousand.
 *
 * The map exists to record STRUCTURE — subsystems, edges, fan-in/out — all of
 * which are stable. Exact line counts are not: they move on every commit that
 * touches `src`, so the committed file changed on literally every PR and any two
 * concurrent PRs conflicted on it. That happened on four PRs in a single day,
 * and each one had to be resolved by regenerating.
 *
 * Rounding keeps the signal the number is actually for — relative subsystem size
 * — while making the file change only when a subsystem moves by ~500 lines, which
 * is a change worth seeing. It also makes the CI drift check mean something:
 * it now fires on real structural drift instead of on every edit.
 */
function kLines(lines: number): string {
  if (lines < 1000) {
    return "<1k";
  }

  return `${String(Math.round(lines / 1000))}k`;
}

function subsystemTable(subsystems: readonly ISubsystem[]): string {
  const rows = subsystems.map((s) => {
    const orphan = s.fanIn === 0 && s.fanOut === 0 ? " ⚠️" : "";

    return `| \`${s.id}\`${orphan} | ${s.purpose} | ${s.tier} | ${s.files} | ${kLines(s.lines)} | ${s.fanIn} | ${s.fanOut} |`;
  });

  return [
    "| Subsystem | Purpose | Tier | Files | Lines | Fan-in | Fan-out |",
    "| --- | --- | --- | --- | --- | --- | --- |",
    ...rows,
  ].join("\n");
}

function cycleTable(cycles: readonly ICycle[]): string {
  const rows = cycles.map(
    (c) =>
      `| \`${c.a}\` ↔ \`${c.b}\` | \`${c.aToB.witness}\` → \`${c.aToB.specifier}\` | ` +
      `\`${c.bToA.witness}\` → \`${c.bToA.specifier}\` |`
  );

  return [
    "| Pair | One way | The other |",
    "| --- | --- | --- |",
    ...rows,
  ].join("\n");
}

/** Render the whole map as the Markdown written to `packages/core/ARCHITECTURE.md`. */
export function renderArchitectureMd(arch: IArchitecture): string {
  const orphans = arch.subsystems.filter(
    (s) => s.fanIn === 0 && s.fanOut === 0
  );

  const out: string[] = [
    "# Architecture map",
    "",
    BANNER,
    "",
    `Derived from \`packages/core/src\`: **${arch.subsystems.length} subsystems**, ` +
      `**${arch.totalFiles} files**, **${kLines(arch.totalLines)} lines**, ` +
      `**${arch.edges.length} cross-subsystem edges**.`,
    "",
    "",
    "This page is the exhaustive record: every subsystem, every cross-subsystem edge, and",
    "a `file:line` witness for each claim. For the shape of the system rather than its",
    "inventory, see the hand-drawn map on [Internals](/internals/).",
    "",
    "## Subsystems",
    "",
    subsystemTable(arch.subsystems),
    "",
  ];

  if (orphans.length > 0) {
    out.push(
      "⚠️ marks a subsystem with no imports in either direction inside `src/`. That does",
      "not make it dead — it may be reached only from `tests/` or `scripts/` — but it does",
      "mean the running harness never pulls it in.",
      ""
    );
  }

  out.push(
    "## Mutual dependencies",
    "",
    "Pairs that import each other, with the line proving each direction. Only mutual",
    "pairs are listed: longer cycles exist in a graph this dense, and enumerating them",
    "buries the ones someone can actually go and break.",
    "",
    cycleTable(arch.cycles),
    "",
    "## Adapter seams",
    "",
    "The interfaces an adapter fills in. The core loop may not import an adapter —",
    "`@typescript-eslint/no-restricted-imports` in `eslint.config.js` enforces it — so",
    "everything stack-specific arrives through one of these.",
    "",
    "| Seam | Declared | Files referencing it |",
    "| --- | --- | --- |",
    ...arch.seams.map(
      (s) =>
        `| \`${s.name}\` | \`${s.declaredAt}\` | ${s.implementors.length} |`
    ),
    "",
    "## Entry points",
    "",
    "Async functions returning an exit code, declared under the CLI — the commands.",
    "",
    "| Function | Declared |",
    "| --- | --- |",
    ...arch.entryPoints.map((e) => `| \`${e.fn}\` | \`${e.at}\` |`),
    ""
  );

  if (arch.externals.length > 0) {
    out.push(
      "## Imports that leave `src/`",
      "",
      "`src/` reaching into `scripts/` inverts the house rule that scripts orchestrate",
      "and `src/` decides — logic imported this way sits where tests are not looking.",
      "",
      "| From | Import | Target |",
      "| --- | --- | --- |",
      ...arch.externals.map(
        (e) => `| \`${e.from}\` | \`${e.witness}\` | \`${e.target}\` |`
      ),
      ""
    );
  }

  out.push(
    "## What this map does not cover",
    "",
    "Stated so a gap is not mistaken for a clean result:",
    "",
    "- Dynamic `import()` and `createRequire` are not followed — only static imports.",
    "- `tests/` and `scripts/` are not scanned; only imports *into* them are noted above.",
    "- Coupling through shared global state or the filesystem is invisible here.",
    "- Only mutual dependency pairs are reported, not longer cycles.",
    ""
  );

  return out.join("\n");
}
