/** A throwaway prefix the model may always write to — `scratch/` experiments are
 *  ignored by the gate, so it can test hypotheses by running code. */
export const SCRATCH_PREFIX = "scratch/";

/**
 * The ONLY file the model must never rewrite: the GENERATED TanStack route tree
 * (`*.gen.ts`), regenerated by the Vite build on every run — hand-edits are lost
 * and pointless. Everything else the scaffold lays down is now clean, strict, and
 * EDITABLE like any other file (the old vendored SDK — api/use-resource/result/…
 * — was removed; it shipped `as` casts + eslint-disable that contradicted the
 * harness's own strictness and trapped the model on files it couldn't fix). The
 * model writes its own data layer, gated like everything else. Applied only to
 * web-scaffold sessions via `IToolContext.vendored`.
 */
export const WEB_VENDORED_PATTERNS = ["**/*.gen.ts"] as const;
