import { mkdtemp, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { randomUUID } from "node:crypto";
import type { IToolCall } from "../../inference";
import { isRecord } from "../../lib/guards";
import { runArgvCommand } from "../../lib/fs";
import { SCRIPT_EXPOSABLE_TOOLS, TOOL_NAME } from "../../agent";
import { LOOP_LIMITS } from "../loop.constants";
import { condenseToolOutput } from "./condense";
import { reject, str, type IToolContext } from "./tool-context";

/** The single tool-dispatch entry the RPC server calls per request. Injected from
 *  execute-tool.ts so script-tool.ts never imports executeTool (no import cycle). */
export type ExecuteFn = (call: IToolCall, ctx: IToolContext) => Promise<string>;

export interface IScriptDeps {
  execute: ExecuteFn;
}

const DEFAULT_TIMEOUT_MS = 60_000;
const MAX_TIMEOUT_MS = 300_000;
const DEFAULT_MAX_CALLS = 50;

function envInt(name: string, fallback: number, max: number): number {
  const raw = process.env[name];
  const parsed = raw === undefined ? NaN : Number.parseInt(raw, 10);

  if (Number.isFinite(parsed) && parsed > 0) {
    return Math.min(parsed, max);
  }

  return fallback;
}

function timeoutMs(args: Record<string, unknown>): number {
  const value = args.timeoutMs;

  if (typeof value === "number" && Number.isFinite(value) && value > 0) {
    return Math.min(Math.floor(value), MAX_TIMEOUT_MS);
  }

  return envInt(
    "TSFORGE_SCRIPT_TIMEOUT_MS",
    DEFAULT_TIMEOUT_MS,
    MAX_TIMEOUT_MS
  );
}

/** Script-exposable tools whose entire required-arg set is a single string param,
 *  so a script may call them POSITIONALLY — `read("a.ts")`, `run("bun test")`,
 *  `search("TODO")` — the natural JS idiom. The stub wraps the bare string into
 *  the named arg. Without this the RPC server coerces the non-object arg to `{}`
 *  (see `handle`), the tool rejects for the missing field, and the rejection TEXT
 *  comes back as the call's RESULT — which a script silently treats as data.
 *  (Observed: a `migrate` run called `read("svcN.ts")` 16× inside a script, each
 *  silently returned the rejection string, the script's regex found "no tier",
 *  and the model spiralled to a stuck-fail never seeing the reads were rejected.)
 *  Multi-arg tools (edit/create/…) are intentionally absent: a positional string
 *  is ambiguous there. Drift-guarded by a test against the real tool schemas. */
export const SCRIPT_POSITIONAL_ARG: Readonly<Record<string, string>> = {
  [TOOL_NAME.read]: "file",
  [TOOL_NAME.run]: "command",
  [TOOL_NAME.search]: "pattern",
};

/** The stub module the script imports as `./tsforge-tools`. One async function per
 *  exposed tool, each POSTing `{tool,args}` to the loopback RPC server with the
 *  one-time token. Plain JS (no type annotations) so `bun run` needs no config.
 *  Tools in `SCRIPT_POSITIONAL_ARG` also accept a bare string, wrapped into the
 *  named arg so the natural positional call shape works. */
export function generateToolStubs(exposed: readonly string[]): string {
  const fns = exposed
    .map((name) => {
      const positional = SCRIPT_POSITIONAL_ARG[name];
      const coerce =
        positional === undefined
          ? "args ?? {}"
          : `typeof args === "string" ? { ${JSON.stringify(positional)}: args } : (args ?? {})`;

      return `export async function ${name}(args = {}) { return __call(${JSON.stringify(name)}, ${coerce}); }`;
    })
    .join("\n");

  return `// AUTO-GENERATED by tsforge — do not edit. Tool stubs for the script sandbox.
const __URL = process.env.TSFORGE_RPC_URL;
const __TOKEN = process.env.TSFORGE_RPC_TOKEN;

async function __call(tool, args) {
  const res = await fetch(__URL, {
    method: "POST",
    headers: { "content-type": "application/json", "x-tsforge-token": __TOKEN },
    body: JSON.stringify({ tool, args: args ?? {} }),
  });
  let data;
  try {
    data = await res.json();
  } catch {
    throw new Error(\`tsforge tool \${tool}: bad RPC response\`);
  }
  if (!res.ok || typeof data?.error === "string") {
    throw new Error(data?.error ?? \`tsforge tool \${tool} failed\`);
  }
  return data.result;
}

${fns}
`;
}

interface IRpcOutcome {
  result?: string;
  error?: string;
}

/** Run `fn`s strictly one at a time (single-slot chain) so concurrent script tool
 *  calls never interleave a mutation through the shared tool context. */
function makeSerializer(): <T>(fn: () => Promise<T>) => Promise<T> {
  let tail: Promise<unknown> = Promise.resolve();

  return <T>(fn: () => Promise<T>): Promise<T> => {
    const run = tail.then(fn, fn);

    tail = run.then(
      () => undefined,
      () => undefined
    );

    return run;
  };
}

interface IScriptServer {
  url: string;
  token: string;
  stop: () => void;
  callCount: () => number;
}

function startRpcServer(ctx: IToolContext, deps: IScriptDeps): IScriptServer {
  const token = randomUUID();
  const maxCalls = envInt("TSFORGE_SCRIPT_MAX_CALLS", DEFAULT_MAX_CALLS, 1_000);
  const serialize = makeSerializer();
  let calls = 0;

  async function handle(req: Request): Promise<IRpcOutcome> {
    if (req.headers.get("x-tsforge-token") !== token) {
      return { error: "forbidden" };
    }

    const body: unknown = await req.json();
    const tool =
      isRecord(body) && typeof body.tool === "string" ? body.tool : "";
    const rawArgs = isRecord(body) ? body.args : undefined;
    const args = isRecord(rawArgs) ? rawArgs : {};

    if (tool === TOOL_NAME.script || !SCRIPT_EXPOSABLE_TOOLS.has(tool)) {
      return { error: `tool \`${tool}\` is not callable from a script` };
    }

    calls += 1;

    if (calls > maxCalls) {
      return {
        error: `script tool-call limit (${String(maxCalls)}) exceeded — do the rest in another turn`,
      };
    }

    ctx.report({
      kind: "tool",
      task: ctx.task,
      message: `↳ script:${tool}`,
    });

    // A tool call that FAILS inside a script reports a `tool_(input_)?rejected:`
    // event and returns the rejection reason as its result STRING. Handing that
    // back as a normal value lets the script silently treat the reason as data —
    // a migrate run edited 8 files this way (each `tool_input_rejected:edit`),
    // printed "Updated …", exited 0, and the model never saw the edits failed.
    // Watch for the rejection event and surface it as an RPC error so the stub
    // THROWS: the script fails loudly with the real reason instead of carrying on.
    const rejections: string[] = [];
    const watched: IToolContext = {
      ...ctx,
      report: (event) => {
        if (
          event.kind === "tool" &&
          /^tool_(?:input_)?rejected:/u.test(event.message)
        ) {
          rejections.push(event.message);
        }

        ctx.report(event);
      },
    };

    const result = await serialize(() =>
      deps.execute({ name: tool, arguments: args }, watched)
    );

    return rejections.length > 0
      ? { error: `${tool} rejected: ${result}` }
      : { result };
  }

  const server = Bun.serve({
    hostname: "127.0.0.1",
    port: 0,
    async fetch(req) {
      const outcome = await handle(req).catch((err: unknown) => ({
        error: err instanceof Error ? err.message : "rpc error",
      }));
      const status = outcome.error === "forbidden" ? 403 : 200;

      return Response.json(outcome, { status });
    },
  });

  return {
    url: `http://127.0.0.1:${String(server.port)}/call`,
    token,
    stop: () => {
      void server.stop(true);
    },
    callCount: () => calls,
  };
}

interface IRunResult {
  exitCode: number;
  output: string;
}

async function runScript(
  scriptPath: string,
  cwd: string,
  env: Record<string, string>,
  budgetMs: number,
  signal: AbortSignal | undefined
): Promise<IRunResult> {
  // Route through the ONE shared runner instead of a bespoke Bun.spawn: it spawns
  // `detached` and kills the whole process GROUP on timeout/abort, so a
  // `(sleep …; touch x) &` backgrounded inside the script can't outlive the kill
  // and mutate the workspace after the tool returns — and its final output drain
  // is always FLUSH_GRACE_MS-bounded, so an orphan holding the pipe open can't
  // stall the tool. A bespoke spawn here did neither.
  const run = await runArgvCommand(cwd, ["bun", "run", scriptPath], {
    env,
    timeoutMs: budgetMs,
    ...(signal === undefined ? {} : { signal }),
  });

  // runArgvCommand only reports `timedOut` for the kill-timeout; an abort kills
  // without that flag, so distinguish the two from the signal state for the note.
  const note = run.timedOut
    ? `\n[script killed: exceeded ${String(budgetMs)}ms timeout]`
    : signal?.aborted === true
      ? "\n[script aborted]"
      : "";

  return {
    exitCode: run.exitCode,
    output: `${run.stdout}${run.stderr}${note}`,
  };
}

/**
 * `script` — run one TypeScript program that calls tools through generated RPC
 * stubs, collapsing a multi-step tool chain into a SINGLE model turn. Every stub
 * call routes back through `executeTool` (deps.execute), so scope, the unified
 * policy, the write-guard, mutation accounting, and the gate all still apply — the
 * model gets ergonomics, not new powers. Only the script's stdout returns to the
 * model. Bounded by a wall-clock timeout, a per-script tool-call cap, and output
 * condensing. NOT offered in plan mode (it can write), and it cannot call itself.
 */
export async function doScript(
  args: Record<string, unknown>,
  ctx: IToolContext,
  deps: IScriptDeps
): Promise<string> {
  const code = str(args, "code").trim();

  if (code.length === 0) {
    return reject(
      ctx,
      "script",
      "script: `code` must be a non-empty TypeScript program (import tools from `./tsforge-tools`)."
    );
  }

  ctx.report({ kind: "tool", task: ctx.task, message: "↳ script" });

  // Inside the workspace (hidden, dot-prefixed) — NOT the system tmp dir — so the
  // script resolves the project's `node_modules` and relative imports by walking
  // up from here to ctx.cwd. The dot prefix keeps eslint/tsc from picking it up,
  // and it is removed in `finally`. Server starts INSIDE the try so a throw there
  // can't leak the dir.
  const dir = await mkdtemp(join(ctx.cwd, ".tsforge-script-"));
  let server: IScriptServer | undefined;

  try {
    server = startRpcServer(ctx, deps);
    await writeFile(
      join(dir, "tsforge-tools.ts"),
      generateToolStubs([...SCRIPT_EXPOSABLE_TOOLS])
    );

    const scriptPath = join(dir, "script.ts");

    await writeFile(scriptPath, code);

    const { exitCode, output } = await runScript(
      scriptPath,
      ctx.cwd,
      {
        ...process.env,
        // The script's stdout is CAPTURED (parsed by the loop, matched in tests),
        // never shown live in a terminal — so any ANSI colorization is corruption,
        // not presentation. Bun colorizes console.log values (e.g. a numeric
        // `403` → `\x1b[33m403\x1b[0m`) whenever it detects color support, which
        // makes captured output non-deterministic across TTY/no-TTY (a literal
        // "STATUS 403" match passes in CI but breaks under the local pre-push).
        // Force color OFF so captured output is plain and stable everywhere.
        NO_COLOR: "1",
        FORCE_COLOR: "0",
        TSFORGE_RPC_URL: server.url,
        TSFORGE_RPC_TOKEN: server.token,
      },
      timeoutMs(args),
      ctx.signal
    );

    const { text } = condenseToolOutput(
      { command: "script", output, exitCode },
      LOOP_LIMITS.maxToolOutputChars
    );

    ctx.report({
      kind: "run",
      task: ctx.task,
      message: "$ script",
      command: "script",
      exitCode,
      output: text,
    });

    return `script exit ${String(exitCode)} (${String(server.callCount())} tool call${server.callCount() === 1 ? "" : "s"})\n${text}`;
  } finally {
    server?.stop();
    await rm(dir, { recursive: true, force: true });
  }
}
